apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: vote
  labels:
    app: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-deployment
  template:
    metadata:
      labels:
        app: db-deployment
    spec:
      containers:
      - name: postgres-db
        image: postgres:9.4
        env:
        - name: POSTGRES_PASSWORD
          value: assignment
        volumeMounts:
        - name: db-data
          mountPath: '/var/lib/postgresql/data'
      volumes:
      - name: db-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: vote
spec:
  selector:
    app: db-deployment
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432